# Generated by Django 5.0.3 on 2024-04-19 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('type', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='student_help.poste')),
                ('location', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('contactInfo', models.CharField(max_length=100)),
            ],
            bases=('student_help.poste',),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='student_help.poste')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('contactInfo', models.CharField(max_length=100)),
            ],
            bases=('student_help.poste',),
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='student_help.poste')),
                ('typeStg', models.IntegerField()),
                ('company', models.CharField(max_length=100)),
                ('period', models.IntegerField()),
                ('topic', models.CharField(max_length=100)),
                ('contactInfo', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
            ],
            bases=('student_help.poste',),
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='student_help.poste')),
                ('begin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('hourBegin', models.TimeField()),
                ('nbrSeat', models.IntegerField()),
            ],
            bases=('student_help.poste',),
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('like', models.BooleanField()),
                ('react', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_help.poste')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_help.user')),
            ],
        ),
        migrations.AddField(
            model_name='poste',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_help.user'),
        ),
        migrations.CreateModel(
            name='EventClub',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='student_help.event')),
                ('club', models.CharField(max_length=100)),
            ],
            bases=('student_help.event',),
        ),
        migrations.CreateModel(
            name='EventSocial',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='student_help.event')),
                ('prix', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            bases=('student_help.event',),
        ),
    ]
