# Generated by Django 5.0.3 on 2024-04-19 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_help', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='student_help.poste')),
                ('text', models.CharField(max_length=100)),
            ],
            bases=('student_help.poste',),
        ),
    ]
