# Generated by Django 5.0.3 on 2024-05-20 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_help', '0002_recommandation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='poste',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='student_help.user'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to='student_help.poste')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_help.user')),
            ],
        ),
    ]
