# Generated by Django 5.0.3 on 2024-05-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_help', '0003_alter_poste_date_alter_poste_user_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
