# Generated by Django 5.0.3 on 2024-05-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_help', '0008_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='stage',
            name='typeStg',
            field=models.IntegerField(choices=[(1, 'Ouvrier'), (2, 'Technicien'), (3, 'PFE')]),
        ),
    ]
